### ISSUE TITLE
Tutorial for longitudinal data

### ISSUE THREAD

**Issue by jamesdalg** [JakubStats/marge#1]
I'm trying to use your package and think it's a really neat idea, but is there some example data/code I can use to see how the GEE model is done/formatted? The tutorial only shows a GLM and the key idea of MARGE is that it does GEEs.

**Comment by JakubStats** [comment]
Hi James,

I've now updated the marge R-package and the vignette which now documents fitting a GEE/MARS model on longitudinal data. This is now called Example 1.

Hope that helps.

**Comment by jamesdalg** [comment]
Perfect! Thanks! I'll see how it works out for my data.
