### ISSUE TITLE
Question: variable cluster size

### ISSUE THREAD

**Issue by jamesdalg** [JakubStats/marge#2]
I have data that doesn't have measurements at every timepoint and can be considered missing at random (scRNAseq data). Is there a way to use nonfixed cluster sizes?

**Comment by JakubStats** [comment]
Yes, it should be able to handle nonfixed cluster sizes now. I've been meaning to implement varying cluster sizes into marge for a while but never got around to it. The latest package version has this implemented, but please let me know if you get any bugs. 

The argument "n" is now the max. cluster size and the "id" argument should be set to identify which cluster the observation is in.

Here's an example with an uneven number of clusters:

library(marge)

is.gee <- TRUE
nb <- FALSE

_Suppose we have N = 5 individuals/clusters but we have variable cluster sizes. 

For example, suppose there are 2 measurements for the first individual/cluster, then 4 measurements for the second and third individual/cluster, 3 measurements for the fourth individual/cluster, and 1 for the 5th individual/cluster._

N <- 5  # Number of clusters.
n <- 4    # Max. cluster size.
id <- c(1, 1, rep(c(2:(N - 2)), each = n), 4, 4, 4, 5)

corstr <- "independence"
family <- "gaussian"

x <- scale(1:length(id))
beta <- c(1, 1)
lp <- cbind(rep(1, length(id)), x)%*%beta
Y <- rnorm(length(id), mean = lp, sd = 1)

X_pred <- as.matrix(x)  # Predictors.
colnames(X_pred) <- "x1"

tols <- 0.00001  # Threshold for stopping condition in forward pass.
tols_score <- 0.00001  # Tolerance for stopping condition in forward pass for MARGE.
M <- 21  # Max. no. of terms.
pen <- 2 # Penalty in GCV.
minspan <- round((-log2(-(1/(ncol(X_pred)*nrow(X_pred)))*log(1 - 0.05))/2.5)) # Minspan value.
print.disp <- FALSE

model_marge <- marge(X_pred, Y, N, n, id, family, corstr, pen, tols_score,
                         M, minspan, print.disp, nb, is.gee)

**Comment by jamesdalg** [comment]
Perfect! I'll try it. Thanks so much again!
